#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-xmlenc
Version  : 0.52
Release  : 1
URL      : https://repo1.maven.org/maven2/xmlenc/xmlenc/0.52/xmlenc-0.52.jar
Source0  : https://repo1.maven.org/maven2/xmlenc/xmlenc/0.52/xmlenc-0.52.jar
Source1  : https://repo1.maven.org/maven2/xmlenc/xmlenc/0.52/xmlenc-0.52.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-xmlenc-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-xmlenc package.
Group: Data

%description data
data components for the mvn-xmlenc package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/xmlenc/xmlenc/0.52
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/xmlenc/xmlenc/0.52

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xmlenc/xmlenc/0.52
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/xmlenc/xmlenc/0.52


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/xmlenc/xmlenc/0.52/xmlenc-0.52.jar
/usr/share/java/.m2/repository/xmlenc/xmlenc/0.52/xmlenc-0.52.pom
